### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by jpswing** [hatsuroku/soj_front-end#4]
1. 在加题页面，把 Memory Limit 的单位改成 MB，并把默认值改成 256，传给后端之前乘个 1024 就好了
2. 把 checker type 里面每个类型都加个说明，就像图中这样，把不在图中的 type（除了 same 和 special judge）删掉
![image](https://user-images.githubusercontent.com/41479689/79722783-426abf80-8317-11ea-8a05-9b6d54bc1997.png)
3. 把显示的语言改成
C++ (G++ 8.3.0 C++17)
C (GCC 8.3.0 C11)
Java 11 (OpenJDK 11.0.5)
Python 3.8 (CPython)
Python 3.6 (PyPy 7.3.1)
把 go 和 js 删了吧。
4. 这个复制按钮的 hover 效果其实是要 hover 在整个大框上的时候就显示出来，要 hover 在按钮上才显示的话估计没人会注意到这个按钮
![image](https://user-images.githubusercontent.com/41479689/79726485-75b04d00-831d-11ea-980d-4f6da629bccd.png)
5. 注册的时候需要二次确认密码
6. 这个 Id 改成 ID
![image](https://user-images.githubusercontent.com/41479689/79726950-2f0f2280-831e-11ea-8d9e-9021b859e11f.png)
7. 这里的文案改成 test solution and generate answer files 吧
![image](https://user-images.githubusercontent.com/41479689/79727118-72699100-831e-11ea-98d0-fa11b2dfad30.png)

**Comment by hatsuroku** [comment]
修改完毕。
